### PR TITLE
Change variable names

### PR DESCRIPTION
**Pull request by pratyushprakash**
Variable names have been changes as mentioned in Issue #31

### CODE REVIEW

**Comment by ankitaggarwal011** [comment]
Good work @pratyushprakash. There are a lot more variables and methods that can use better and more intuitive naming. Please let me know if you are still working on them and want to include more commits in this request. Thank you for your contribution.

**Comment by pratyushprakash** [comment]
@ankitaggarwal011 The thing is I don't understand CNN's very well so I could not understand what the methods were doing and what the variables represented

**Comment by ankitaggarwal011** [comment]
@pratyushprakash, don't worry about it. Please resolve the current conflicts with this request and I'll merge it in its current state. However, this doesn't close the respective issue, so please comment on the issue that it requires work and that your not working on it anymore such that other interested people can start working on it. Thank you for your contribution.

**Comment by ankitaggarwal011** [comment]
@pratyushprakash, please update your branch with the latest code on master branch and then add your commits, currently it's recommiting the changes that have been already merged. Thanks.

**Comment by ankitaggarwal011** [comment]
@pratyushprakash, would you please resolve the problem and we can close it.

**Comment by pratyushprakash** [comment]
@ankitaggarwal011 How do I remove the previous commits?

**Comment by ankitaggarwal011** [comment]
@pratyushprakash, since doc-strings had been introduced in the code, you would need to rename variables in that as well. You can either reset the recent commits, pull the latest master branch, and make your changes or start afresh in a new branch and a new pull request. 

I would suggest you to start afresh, but I would request you this time to try to incorporate more changes with respect to renaming the variables. I would help you out wherever required. Thank you.

**Comment by ankitaggarwal011** [comment]
The request has been updated as #34. Closing this one.

**Pull request closed without merging**
