### PR TITLE
PEP8 Compliance

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
@ankitaggarwal011 Can you please check the travis build :sweat_smile:

**Comment by ankitaggarwal011** [comment]
@SubhrajyotiSen, I was in the process of merging another commit and setup Travis CI, please ignore current warnings, I'll take care of it. Thank you so much for your contribution. I'll review this request and get back to you.

**Comment by ankitaggarwal011** [comment]
@SubhrajyotiSen, please ignore Travis CI checks at this time. The project is still not PEP8 compliant after the changes you've made, especially the number of allowed characters in a line. Please consider reviewing the file. Thank you for your contribution. Furthermore, it would be nice to add PEP8 compliance with Travis CI.

Edit: Please pull and commit the latest changes on your branch in order to pass the Travis CI tests.

**Comment by SubhrajyotiSen** [comment]
@ankitaggarwal011 I have corrected the issue with the line lengths.

**Comment by ankitaggarwal011** [comment]
@SubhrajyotiSen, excellent work. Thank you for your contribution. 

Edit: Would you be to check the compliance for the other code files, and open a separate request in case an improvement is required. Thanks.

**Pull request merged**
