### PR TITLE
Fix issue 29 oo ode

### PR DESCRIPTION
**Pull request by pjbollinger**
This is to add scipy.integrate.ode to the project and allow for the more object-oriented friendly ODE instead of the previous scipy.integrate.odeint functionality.

This should resolve Issue #29.

I made some other modifications to allow for the new ode function.

You can see that this passes all tests found here: [https://codecov.io/gh/pjbollinger/PyCNN/commit/52dc7e8b60d0df1a586a674670599af08cef1bd9](https://codecov.io/gh/pjbollinger/PyCNN/commit/52dc7e8b60d0df1a586a674670599af08cef1bd9)

### CODE REVIEW

**Comment by ankitaggarwal011** [comment]
Good work @pjbollinger. I just have a doubt about why you have increased the number of time samples by 1 in each of the example. Thanks.

**Review by ankitaggarwal011 — COMMENTED** [review]
I have a doubt about why you have increased the number of time samples by 1 in each of the example. Thanks.

**Comment by pjbollinger** [comment]
The reason for that is to create cleaner looking arrays. Below are examples.

``` python
>>> np.linspace(0.0, 10.0, num=10)
[0.0, 1.11111111, 2.2222222, 3.333333, ... , 8.8888888, 10.0]
>>> np.linspace(0.0, 10.0, num=11)
[0.0, 1.0, 2.0, 3.0, ..., 8.0, 9.0, 10.0]
```

Please verify if you would like, I don't have access to Python/NumPy at the moment so the result might not be exact.

**Comment by ankitaggarwal011** [comment]
That works @pjbollinger. Thank you for your contribution. Excellent work!

**Pull request merged**
