### PR TITLE
Minor code cleanup

### PR DESCRIPTION
**Pull request by raj454raj**

### CODE REVIEW

**Comment by raj454raj** [comment]
@ankitaggarwal011 : Please review.

**Comment by ankitaggarwal011** [comment]
@raj454raj, Thank you for your contribution. Please make sure your using the latest code-base, the last commit is not updated in your code. Furthermore, please make sure that your code is PEP8 compliant. Thanks and Good work!

**Comment by raj454raj** [comment]
@ankitaggarwal011 : There are no merge conflicts with this PR, you won't face any problems if you merge this. (PS: It already has your latest commits.)

**Comment by ankitaggarwal011** [comment]
@raj454raj, thank you for looking into this. Earlier the last commit was only partially updated, now your version seems to be up-to-date. Great work! Thank you for your contribution.

**Pull request merged**
