### PR TITLE
Upgrade to Pillow and port to Python3

### PR DESCRIPTION
**Pull request by liviu-**
I noticed the 2 issues you've opened (#4 and #3), and I gave it a shot to port the codebase to Python3. Please let me know your thoughts.

### CODE REVIEW

**Comment by ankitaggarwal011** [comment]
This is great work @liviu- ! I appreciate your contribution. 

Is the API for Pillow and Image module exactly the same for the functions of interest here? If yes, that's great!

Do you think using print statements directly without `from __future__ import print_function` in python 2 would have any negative effect for their usage in the library?

Please let me know what you think about it. I'll test these changes and if everything works well, we will be good to merge these changes. Thanks again. Appreciate it!

**Comment by liviu-** [comment]
> This is great work @liviu- ! I appreciate your contribution. 

Thanks! And thanks for the project :stuck_out_tongue: 

> Is the API for Pillow and Image module exactly the same for the functions of interest here? If yes, that's great!

Seems like it. Pillow is a fork of the old PIL, and they removed support for `import Image` in [v1.0](https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#10-07302010) when they replaced it with `from PIL import Image`.

> Do you think using print statements directly without from **future** import print_function in python 2 would have any negative effect for their usage in the library?

You're right; I added another commit to import `print_function`. It works fine without it for simple printing commands, but it wouldn't work for more complex instances (e.g. `print(str, sep=',')`)

Let me know if there's any other issue I can help out with.

**Comment by ankitaggarwal011** [comment]
@liviu-, great work! I read about porting from Python 2 to 3 from [here](https://docs.python.org/3/howto/pyporting.html) and [here](http://python-future.org/compatible_idioms.html). I ran the futurize script to check the compatibility of the code with Python 3 and everything else is compatible other than the print statements. Moreover, the packages numpy, scipy and pillow are all python 2/3 compatible. I ran the tests with tox and it was successful with both versions of Python.

So, this request would close issues #2, #3, and #4. 

Other than this, I wanted to take this opportunity to check compatibility with the updated versions of the numpy, and scipy packages, but that can be checked in a separate issue.

**Edit:**
@liviu-, I tested the project with 32-bit versions of Pillow (3.3.1), scipy (0.18.0), numpy (1.11.1 +mkl) with Python 27 and Python 35 on 64-bit Windows machine. The project was running successfully.

**Comment by ankitaggarwal011** [comment]
@liviu-, I have merged this request. Great work and thanks for your contribution. Appreciate it!

**Pull request merged**
