### PR TITLE
git workflow added

### PR DESCRIPTION
**Pull request by iabhi7**
I have added the following points mentioned in Issue #14 
a) How to contribute - improve documentation/add new methods/improve performance.
b) Explain contribution workflow - issues/pull-request/review.
Have a look and then I will proceed with the next.

### CODE REVIEW

**Review by ankitaggarwal011 — COMMENTED** [review]
Please review. There are some typos and references to scikit-learn.

**Comment by ankitaggarwal011** [comment]
@vibrantabhi19, keep up the good work. While the GitHub workflow is well explained, it doesn't document a) How to contribute - improve documentation/add new methods/improve performance. Please let me know if you need any help or information. 

Also it might be better to document the overview of code structure and API can be written in a separate document rather than this. You can leave that section at this time. Thank you for your contribution.

**Review by ankitaggarwal011 — COMMENTED** [review]
There are still some typos, please proof-read the text. Thanks.

**Comment by ankitaggarwal011** [comment]
@vibrantabhi19, can you please update on this? Thanks.

**Comment by iabhi7** [comment]
Sure. Will do it within a day.

**Pull request closed without merging**
